name: portfolio
recipe: laravel

config:
  webroot: public
  via: nginx
  php: '8.1'
  composer_version: 2
  xdebug: true

services:
  appserver:
    build:
      - '[ ! -f ".env" ] && cp .env.example .env || echo ".env already present"'
      - composer install
